name: Codeflash

on:
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    name: Optimize new code in this PR
    if: ${{ github.actor != 'codeflash-ai[bot]' }}
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Project Dependencies
      # TODO: Replace the following with your project setup method (e.g. poetry, pip) to install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --all-extras
      - name: Run Codeflash to optimize code
        id: optimize_code
        run: |
          poetry env use python
          poetry run codeflash
